export const countryOptions = [
  { label: 'United States', value: 'US' },
  { label: 'United Kingdom', value: 'GB' },
  { label: 'Canada', value: 'CA' },
  { label: 'Australia', value: 'AU' },
  { label: 'Germany', value: 'DE' },
  { label: 'France', value: 'FR' },
  { label: 'Italy', value: 'IT' },
  { label: 'Spain', value: 'ES' },
  { label: 'Netherlands', value: 'NL' },
  { label: 'Belgium', value: 'BE' },
  { label: 'Switzerland', value: 'CH' },
  { label: 'Sweden', value: 'SE' },
  { label: 'Norway', value: 'NO' },
  { label: 'Denmark', value: 'DK' },
  { label: 'Finland', value: 'FI' },
  { label: 'Poland', value: 'PL' },
  { label: 'Portugal', value: 'PT' },
  { label: 'Ireland', value: 'IE' },
  { label: 'Austria', value: 'AT' },
  { label: 'Greece', value: 'GR' },
  { label: 'Japan', value: 'JP' },
  { label: 'South Korea', value: 'KR' },
  { label: 'Singapore', value: 'SG' },
  { label: 'Hong Kong', value: 'HK' },
  { label: 'India', value: 'IN' },
  { label: 'China', value: 'CN' },
  { label: 'Brazil', value: 'BR' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Argentina', value: 'AR' },
  { label: 'South Africa', value: 'ZA' },
  { label: 'Nigeria', value: 'NG' },
  { label: 'Kenya', value: 'KE' },
  { label: 'Egypt', value: 'EG' },
  { label: 'United Arab Emirates', value: 'AE' },
  { label: 'Saudi Arabia', value: 'SA' },
  { label: 'Israel', value: 'IL' },
  { label: 'Turkey', value: 'TR' },
  { label: 'Russia', value: 'RU' },
  { label: 'Other', value: 'OTHER' },
]

export const industryOptions = [
  { label: 'Technology', value: 'technology' },
  { label: 'Financial Services', value: 'financial_services' },
  { label: 'Healthcare', value: 'healthcare' },
  { label: 'Education', value: 'education' },
  { label: 'Retail', value: 'retail' },
  { label: 'Manufacturing', value: 'manufacturing' },
  { label: 'Real Estate', value: 'real_estate' },
  { label: 'Consulting', value: 'consulting' },
  { label: 'Legal', value: 'legal' },
  { label: 'Marketing & Advertising', value: 'marketing_advertising' },
  { label: 'Media & Entertainment', value: 'media_entertainment' },
  { label: 'Telecommunications', value: 'telecommunications' },
  { label: 'Energy', value: 'energy' },
  { label: 'Transportation & Logistics', value: 'transportation_logistics' },
  { label: 'Hospitality & Tourism', value: 'hospitality_tourism' },
  { label: 'Food & Beverage', value: 'food_beverage' },
  { label: 'Construction', value: 'construction' },
  { label: 'Agriculture', value: 'agriculture' },
  { label: 'Pharmaceuticals', value: 'pharmaceuticals' },
  { label: 'Automotive', value: 'automotive' },
  { label: 'Aerospace', value: 'aerospace' },
  { label: 'Government', value: 'government' },
  { label: 'Non-Profit', value: 'non_profit' },
  { label: 'Other', value: 'other' },
]

export const roleOptions = [
  { label: 'CEO / Founder', value: 'ceo_founder' },
  { label: 'CTO / Technical Director', value: 'cto_technical_director' },
  { label: 'CFO', value: 'cfo' },
  { label: 'COO', value: 'coo' },
  { label: 'VP / Vice President', value: 'vp' },
  { label: 'Director', value: 'director' },
  { label: 'Manager', value: 'manager' },
  { label: 'Senior Manager', value: 'senior_manager' },
  { label: 'Team Lead', value: 'team_lead' },
  { label: 'Senior Developer', value: 'senior_developer' },
  { label: 'Developer / Engineer', value: 'developer_engineer' },
  { label: 'Product Manager', value: 'product_manager' },
  { label: 'Project Manager', value: 'project_manager' },
  { label: 'Business Analyst', value: 'business_analyst' },
  { label: 'Data Analyst', value: 'data_analyst' },
  { label: 'Data Scientist', value: 'data_scientist' },
  { label: 'Security Engineer', value: 'security_engineer' },
  { label: 'DevOps Engineer', value: 'devops_engineer' },
  { label: 'QA Engineer', value: 'qa_engineer' },
  { label: 'UX/UI Designer', value: 'ux_ui_designer' },
  { label: 'Marketing Manager', value: 'marketing_manager' },
  { label: 'Sales Manager', value: 'sales_manager' },
  { label: 'HR Manager', value: 'hr_manager' },
  { label: 'Operations Manager', value: 'operations_manager' },
  { label: 'Consultant', value: 'consultant' },
  { label: 'Freelancer', value: 'freelancer' },
  { label: 'Student', value: 'student' },
  { label: 'Other', value: 'other' },
]

export const companySizeOptions = [
  { label: '1-10 employees', value: '1-10' },
  { label: '11-50 employees', value: '11-50' },
  { label: '51-200 employees', value: '51-200' },
  { label: '201-500 employees', value: '201-500' },
  { label: '501-1000 employees', value: '501-1000' },
  { label: '1001-5000 employees', value: '1001-5000' },
  { label: '5001-10000 employees', value: '5001-10000' },
  { label: '10000+ employees', value: '10000+' },
]
